name: my first pipeline

on: push

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository code
          uses: actions/checkout@v4
        - name: Build image
          run: docker build -t malvinerye/cipotfolio .
        - name: List images  
          run: docker images
           

    


 